name: tripmanager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  provider: any
  google_fonts: any
  email_validator: any
  carousel_slider: any
  scrollable_positioned_list: any
  open_filex: any
  permission_handler: any
  url_launcher: any
  http: any
  firebase_core: any
  cloud_firestore: any
  firebase_storage: any
  floating_snackbar: any
  image_picker: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: any
flutter_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/play_store_512.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/
